services:
  lvim-tmux:
    container_name: lvim-tmux
    image: lvim-tmux
    build:
      context: .
      args:
        - USER=${USER}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - /home/${USER}:/home/${USER}/dev
      - /home/${USER}/.ssh/:/home/${USER}/.ssh/
    stdin_open: true
    tty: true
    restart: always
    environment:
      - GIT_CONFIG_GLOBAL=/home/${USER}/.gitconfig
    env_file: .env
    command: ["/bin/bash", "--login"]
    init: true
    networks:
      - lvim-tmux-network

networks:
  lvim-tmux-network: {name: lvim-tmux-network}
