# sudo docker-compose up -d
# docker exec -it lvim-tmux tmux

version: "3"
services:
  lvim-tmux:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        - USER=${USER}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - /home/${USER}:/home/${USER}/dev
      - /home/${USER}/.ssh/id_rsa:/home/${USER}/.ssh/id_rsa
    container_name: lvim-tmux
    env_file: .env
    command: ["/bin/bash", "--login"]
