# sudo docker-compose up -d
# docker exec -it lvim-tmux tmux

version: "3"
services:
  lvim-tmux:
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - /home/${USER}:/root/dev
      - /home/${USER}/.ssh:/root/.ssh
      - /home/${USER}/.gitconfig:/root/.gitconfig
    container_name: lvim-tmux
    env_file: .env
    command: ["/bin/bash", "--login"]
