live_config_reload = true

[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#FF2400"
yellow = "#FDFF00"

[colors.cursor]
cursor = "#FF00FF"
text = "#00FF00"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#0000FF"
foreground = "#222222"

[colors.vi_mode_cursor]
cursor = "#00FF00"
text = "#FF00FF"

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
args = ["exec", "-it", "lvim-tmux", "tmux"]
program = "docker"

[window]
decorations = "None"
opacity = 0.15
startup_mode = "Maximized"
